analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.861162
  lightness: 0.695945
  rhythmicContrast: 0.967905
  saturation: 0.533783
cta: {}
layout_spectrum: 0.984797
name: sWIrvN10
opengraph: {}
purpose: {}
typography_spectrum: 0.827702
