analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#082840'
    - '#6090B0'
    - '#3088C0'
    - '#60B0E0'
  brandStrength: 0.72804
  lightness: 0.516892
  rhythmicContrast: 0.408784
  saturation: 0.47973
cta: {}
layout_spectrum: 0.618243
name: sWIrvN10
opengraph: {}
purpose: {}
typography_spectrum: 0.13357951015983738
