name: sWIrvN10
favicon: null
layout_spectrum: 0.77383
typography_spectrum: 0.13357951015983738
title: Music Enthusiast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
