name: sWIrvN10
favicon: null
layout_spectrum: 0.77383
typography_spectrum: 0.13357951015983738
title: Music Enthusiast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35202636-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040607'
    - '#fefefe'
    - '#3f4041'
    - '#6f7070'
    - '#9a9a9a'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
