analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.79223
  lightness: 0.778717
  rhythmicContrast: 0.891891
  saturation: 0.724662
cta: {}
layout_spectrum: 0.966216
name: sWIrvN10
opengraph: {}
purpose: {}
typography_spectrum: 0.13357951015983738
